context:
  version: "0.1.3"
  python_min: '3.11'

package:
  name: nanonis-xarray
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/n/nanonis-xarray/nanonis_xarray-${{ version }}.tar.gz
    sha256: 966ebd81ca5abfb1c5cdb468d96df8fe37f8831f59ccce8a4a3b16ca65e7bc98

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.26
    - pint-xarray >=0.4
    - xarray >=2023.9.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - nanonis_xarray
      pip_check: true

about:
  homepage: https://github.com/angelo-peronio/nanonis-xarray
  summary: Read a Nanonis spectroscopy .dat file into a xarray Dataset
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
    - angelo-peronio
